name: release

on: # triggered by push tagged commits to main
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }} for python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: ['3.11', '3.12', '3.13']


    steps:

      - name: install X11 dependencies
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          sudo apt install -y libx11-dev libxpm-dev x11proto-dev

      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}

      - name: install python
        run: pip install setuptools

      - run: echo "$USER"
      - run: echo "$HOSTNAME"


      - name: build wheels
        run: python setup.py bdist_wheel | grep "creating 'dist" | sed 's/creating /WHEEL_NAME=/' | cut -f1 -d' ' >> "$GITHUB_ENV"
        working-directory: python
        id: wheels

      - run: echo "$WHEEL_NAME"
      - run: echo ${{ env.WHEEL_NAME }}

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ env.WHEEL_NAME }}
          path: ./python/dist/*.whl


  release:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          path: ./wheelhouse

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./wheelhouse/**/*.whl
          body_path: .github/CHANGELOG.md
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
